SCREEN_WIDTH = 980
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_INVINCIBILITY_DURATION = 3 # seconds
PLAYER_STARTING_HEALTH = 3

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.7  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 30
ASTEROID_SPREAD = 500

SHOT_RADIUS = 3
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.6

BOMB_RADIUS = 5
MAX_BOMB_RADIUS = 75
BOMB_TIMER = 1
PLAYER_BOMB_COOLDOWN = 4

LEVEL_UP_SCORE = 150

PARTICLE_FADE_SPEED = 200